site_name: c4ddev Documentation
docs_dir: source
markdown_extensions:
  - admonition
  - codehilite
  - smarty
theme: material
pages:
  - Home: index.md
  - Changelog: changelog.md
  - Plugins: plugins.md
  - CLI: cli.md
  - Scripting API: api/index.md
  - Contents:
    - Resource Packages: rpkg.md
    - Using Node.py in C4D: nodepy.md
    - Localimport: localimport.md
  - C++ Information:
    - Resources: cpp/resources.md
    - Snippets: cpp/snippets.md
  - Python Information:
    - Async GUI: python/asyncgui.md
    - Scripts & Snippets: python/scripts.md
