site_name: c4ddev Documentation
docs_dir: source
markdown_extensions:
  - admonition
  - codehilite
  - smarty
theme: material
pages:
  - Home: index.md
  - Changelog: changelog.md
  - Plugins:
    - C4D IDE: plugins/c4dide.md
    - PyDrawHelper: plugins/pydrawhelper.md
    - PyShader: plugins/pyshader.md
    - Unicode Escape Tool: plugins/uescapetool.md
  - Command-line Interface:
    - Installation: cli/_install.md
    - build-loader: cli/build-loader.md
    - pip-get: cli/pip-get.md
    - pip: cli/pip.md
    - pypkg: cli/pypkg.md
    - rpkg: cli/rpkg.md
    - symbols: cli/symbols.md
  - Localimport: localimport.md
  - Scripting API: api/index.md
  - C++ Information:
    - Resources: cpp/resources.md
    - Snippets: cpp/snippets.md
  - Python Information:
    - Async GUI: python/asyncgui.md
    - Scripts & Snippets: python/scripts.md
